# site settings
title: IGNITE
subtitle: by HTML5 UP
email: graciellehigino@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/ignite_website" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Goiânia
state: GO
zip_code: 
country: Brazil
phone: +55 (62) 981440564

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/graciellehigino/IGNITE
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/graciellehigino
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/graciellehigino

# build settings
markdown: kramdown

sass:
  style: compressed
